// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8sMH-pkIJIsh09yWGiVeeL3rwF0BUG1c',
    appId: '1:152777030874:web:4f3df667472cb20262b9e3',
    messagingSenderId: '152777030874',
    projectId: 'login-9a6ed',
    authDomain: 'login-9a6ed.firebaseapp.com',
    storageBucket: 'login-9a6ed.firebasestorage.app',
    measurementId: 'G-7PDN0PFHW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV-Mf-0WeD5lR1PMDG4hfqHZt15LwKmFw',
    appId: '1:152777030874:android:73fab5c71b44afaf62b9e3',
    messagingSenderId: '152777030874',
    projectId: 'login-9a6ed',
    storageBucket: 'login-9a6ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe3DIC9hoGCZcpAOud-mOasNRjeWKvSjk',
    appId: '1:152777030874:ios:21ebfb7153a7524962b9e3',
    messagingSenderId: '152777030874',
    projectId: 'login-9a6ed',
    storageBucket: 'login-9a6ed.firebasestorage.app',
    iosBundleId: 'com.example.uberClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe3DIC9hoGCZcpAOud-mOasNRjeWKvSjk',
    appId: '1:152777030874:ios:21ebfb7153a7524962b9e3',
    messagingSenderId: '152777030874',
    projectId: 'login-9a6ed',
    storageBucket: 'login-9a6ed.firebasestorage.app',
    iosBundleId: 'com.example.uberClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8sMH-pkIJIsh09yWGiVeeL3rwF0BUG1c',
    appId: '1:152777030874:web:d122c2c0dbb0739462b9e3',
    messagingSenderId: '152777030874',
    projectId: 'login-9a6ed',
    authDomain: 'login-9a6ed.firebaseapp.com',
    storageBucket: 'login-9a6ed.firebasestorage.app',
    measurementId: 'G-SXL05M3054',
  );
}
